name: Helm Publish

on:
  push:
    branches: [ 'main' ]
  workflow_dispatch:
  
jobs:
  helm:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Helm
        uses: azure/setup-helm@v4.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Run some commands
        run: |
          ls -l 
          pwd
          helm version
          helm lint .

