name: Helm Publish

on:
  push:
    branches: [ 'main' ]
  workflow_dispatch:
  
jobs:
  helm:
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Helm
        uses: azure/setup-helm@v4.2.0
      
      - name: Perform Helm lint
        run: helm lint .
      
      - name: Create Helm package
        run: |
          helm package .
          
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}